### ISSUE TITLE
Raw Image Support

### ISSUE THREAD

**Issue by z430** [python-xmp-toolkit/python-xmp-toolkit#79]
is this library support for editing xmp on raw image? the raw image format can be cr2, arw etc

thanks

**Comment by zougloub** [comment]
This library is supposed to be a thin wrapper over [Exempi](https://libopenraw.freedesktop.org/exempi/) which is a library providing (a simplified) access to XMP. If you are encountering an issue where you can't read/edit xmp on a file, and the error happens when checking Exempi's return codes, then the issue is in Exempi (or Adobe's XMP Toolkit that Exempi wraps).
